# Generated by Django 6.0.6 on 2026-06-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('Novel', 'Novel'), ('Sejarah', 'Sejarah'), ('Pendidikan', 'Pendidikan')], max_length=50)),
                ('penerbit', models.CharField(max_length=150)),
                ('tahun_terbit', models.PositiveIntegerField()),
                ('rak', models.CharField(max_length=20)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Buku',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=20, unique=True, verbose_name='NIS')),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.CharField(blank=True, default='', max_length=100)),
                ('catatan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpustkaan.buku')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpustkaan.siswa')),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-id'],
            },
        ),
    ]
