# Generated by Django 6.0.6 on 2026-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustkaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
